### ISSUE TITLE
Segmentation fault on debian stretch / mariadb 10.2

### ISSUE THREAD

**Issue by nervo** [sensu-plugins/sensu-plugins-percona#6]
Hello,

although we don't have any issues with this plugin on our mysql 5.6/5.7 clusters, we are running into a segmentation fault on our mariadb 10.2 cluster:
```
$ ./check-percona-cluster-size.rb --user xxxxxx --password xxxxxx
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/mysql2-0.4.8/lib/mysql2/mysql2.so: [BUG] Segmentation fault at 0x00000000000000
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0010 p:-11862892039826 s:0057 e:000056 TOP    [FINISH]
c:0009 p:---- s:0054 e:000053 CFUNC  :require
c:0008 p:0132 s:0049 e:000048 METHOD /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55
c:0007 p:0284 s:0037 e:000036 TOP    /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/mysql2-0.4.8/lib/mysql2.rb:31 [FINISH]
c:0006 p:---- s:0033 e:000032 CFUNC  :require
c:0005 p:0132 s:0028 e:000027 METHOD /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55
c:0004 p:0017 s:0016 e:000015 TOP    /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-percona-1.1.0/bin/check-percona-cluster-size.rb:18 [FINISH]
c:0003 p:---- s:0013 e:000012 CFUNC  :load
c:0002 p:0136 s:0008 E:000210 EVAL   ./check-percona-cluster-size.rb:22 [FINISH]
c:0001 p:0000 s:0003 E:000a30 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
./check-percona-cluster-size.rb:22:in `<main>'
./check-percona-cluster-size.rb:22:in `load'
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugins-percona-1.1.0/bin/check-percona-cluster-size.rb:18:in `<top (required)>'
/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/mysql2-0.4.8/lib/mysql2.rb:31:in `<top (required)>'
/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'

-- Machine register context ------------------------------------------------
 RIP: 0x00007fa48f8fd53a RBP: 0x000056505b936c00 RSP: 0x00007ffdb8ddf3a8
 RAX: 0x0000000000000000 RBX: 0x000056505b938700 RCX: 0x0000000000000040
 RDX: 0x0000000000000000 RDI: 0x0000000000000000 RSI: 0x0000000000000000
  R8: 0x000056505b9381c8  R9: 0x0000000000000020 R10: 0x000056505b9376c8
 R11: 0x000000000000001b R12: 0x0000000000000002 R13: 0x000056505bb931b8
 R14: 0x000056505b938720 R15: 0x00007fa48e15cdc0 EFL: 0x0000000000010283

-- C level backtrace information -------------------------------------------
/opt/sensu/embedded/lib/libruby.so.2.4(rb_vm_bugreport+0x4f1) [0x7fa490780631]
/opt/sensu/embedded/lib/libruby.so.2.4(rb_bug_context+0xd4) [0x7fa49060b2a4]
/opt/sensu/embedded/lib/libruby.so.2.4(sigsegv+0x3e) [0x7fa4906f7d1e]
[0x7fa49035e0c0]
[0x7fa48f8fd53a]
[0x7fa48e2018a9]
[0x7fa48e201b60]
[0x7fa48e15d209]
[0x7fa48db42a3c]
[0x7fa48db5a0d9]
[0x7fa49035b739]
[0x7fa48dbaff59]
[0x7fa48db5a533]
[0x7fa48deb1bd4]
[0x7fa48e9e0b4b]
[0x7fa48e9c9ab8]
[0x7fa49035b739]
[0x7fa48ec0a2ac]
[0x7fa48ec0b1d8]
/opt/sensu/embedded/lib/libruby.so.2.4(dln_load+0x115) [0x7fa490598f25]
/opt/sensu/embedded/lib/libruby.so.2.4(rb_vm_call_cfunc+0xa6) [0x7fa490769f36]
/opt/sensu/embedded/lib/libruby.so.2.4(rb_require_internal+0x3df) [0x7fa4906574af]
/opt/sensu/embedded/lib/libruby.so.2.4(rb_require_safe+0x9) [0x7fa490657ab9]
/opt/sensu/embedded/lib/libruby.so.2.4(vm_call_cfunc+0xe7) [0x7fa490764457]
/opt/sensu/embedded/lib/libruby.so.2.4(vm_exec_core+0x1629) [0x7fa49076cea9]
/opt/sensu/embedded/lib/libruby.so.2.4(vm_exec+0x8a) [0x7fa49077247a]
/opt/sensu/embedded/lib/libruby.so.2.4(rb_load_internal0+0xaf) [0x7fa490655b3f]
/opt/sensu/embedded/lib/libruby.so.2.4(rb_require_internal+0x7b1) [0x7fa490657881]
/opt/sensu/embedded/lib/libruby.so.2.4(rb_require_safe+0x9) [0x7fa490657ab9]
/opt/sensu/embedded/lib/libruby.so.2.4(vm_call_cfunc+0xe7) [0x7fa490764457]
/opt/sensu/embedded/lib/libruby.so.2.4(vm_exec_core+0x1629) [0x7fa49076cea9]
/opt/sensu/embedded/lib/libruby.so.2.4(vm_exec+0x8a) [0x7fa49077247a]
/opt/sensu/embedded/lib/libruby.so.2.4(rb_load_internal0+0xaf) [0x7fa490655b3f]
/opt/sensu/embedded/lib/libruby.so.2.4(rb_f_load+0x8b) [0x7fa49065621b]
/opt/sensu/embedded/lib/libruby.so.2.4(vm_call_cfunc+0xe7) [0x7fa490764457]
/opt/sensu/embedded/lib/libruby.so.2.4(vm_call_method+0xe3) [0x7fa490773e73]
/opt/sensu/embedded/lib/libruby.so.2.4(vm_exec_core+0x1629) [0x7fa49076cea9]
/opt/sensu/embedded/lib/libruby.so.2.4(vm_exec+0x8a) [0x7fa49077247a]
/opt/sensu/embedded/lib/libruby.so.2.4(ruby_exec_internal+0xb0) [0x7fa490611050]
/opt/sensu/embedded/lib/libruby.so.2.4(ruby_exec_node+0x1d) [0x7fa490612d8d]
/opt/sensu/embedded/lib/libruby.so.2.4(ruby_run_node+0x1e) [0x7fa490615c6e]
/opt/sensu/embedded/bin/ruby(main+0x4b) [0x56505a6d995b] main.c:36

-- Other runtime information -----------------------------------------------

* Loaded script: ./check-percona-cluster-size.rb

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 /opt/sensu/embedded/lib/ruby/2.4.0/x86_64-linux/enc/encdb.so
    5 /opt/sensu/embedded/lib/ruby/2.4.0/x86_64-linux/enc/trans/transdb.so
    6 /opt/sensu/embedded/lib/ruby/2.4.0/unicode_normalize.rb
    7 /opt/sensu/embedded/lib/ruby/2.4.0/x86_64-linux/rbconfig.rb
    8 /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/compatibility.rb
    9 /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/defaults.rb
   10 /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/deprecate.rb
   11 /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/errors.rb
   12 /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/version.rb
   13 /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/requirement.rb
   14 /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/platform.rb
   15 /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/basic_specification.rb
   16 /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/stub_specification.rb
   17 /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/util/list.rb
   18 /opt/sensu/embedded/lib/ruby/2.4.0/x86_64-linux/stringio.so
   19 /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb
   20 /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/exceptions.rb
   21 /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/dependency.rb
   22 /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_gem.rb
   23 /opt/sensu/embedded/lib/ruby/2.4.0/monitor.rb
   24 /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb
   25 /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems.rb
   26 /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/path_support.rb
   27 /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/version.rb
   28 /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/core_ext/name_error.rb
   29 /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/levenshtein.rb
   30 /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/jaro_winkler.rb
   31 /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checker.rb
   32 /opt/sensu/embedded/lib/ruby/2.4.0/delegate.rb
   33 /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
   34 /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
   35 /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checkers/name_error_checkers.rb
   36 /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checkers/method_name_checker.rb
   37 /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checkers/null_checker.rb
   38 /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/formatter.rb
   39 /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean.rb
   40 /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin.rb
   41 /opt/sensu/embedded/lib/ruby/2.4.0/optparse.rb
   42 /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/mixlib-cli-1.7.0/lib/mixlib/cli.rb
   43 /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/cli.rb
   44 /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-plugin-1.4.5/lib/sensu-plugin/check/cli.rb
   45 /opt/sensu/embedded/lib/ruby/2.4.0/x86_64-linux/date_core.so
   46 /opt/sensu/embedded/lib/ruby/2.4.0/date.rb
   47 /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/bigdecimal-1.3.5/lib/bigdecimal.so
   48 /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/mysql2-0.4.8/lib/mysql2/version.rb
   49 /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/mysql2-0.4.8/lib/mysql2/error.rb

* Process memory map:

56505a6d9000-56505a6da000 r-xp 00000000 07:07 1572936                    /opt/sensu/embedded/bin/ruby
56505a8d9000-56505a8da000 r--p 00000000 07:07 1572936                    /opt/sensu/embedded/bin/ruby
56505a8da000-56505a8db000 rw-p 00001000 07:07 1572936                    /opt/sensu/embedded/bin/ruby
56505b7de000-56505bbdb000 rw-p 00000000 00:00 0                          [heap]
7fa48d5c9000-7fa48d5df000 r-xp 00000000 07:07 1442441                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fa48d5df000-7fa48d7de000 ---p 00016000 07:07 1442441                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fa48d7de000-7fa48d7df000 r--p 00015000 07:07 1442441                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fa48d7df000-7fa48d7e0000 rw-p 00016000 07:07 1442441                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fa48d7e0000-7fa48d7ea000 r-xp 00000000 07:07 1442456                    /lib/x86_64-linux-gnu/libnss_files-2.24.so
7fa48d7ea000-7fa48d9ea000 ---p 0000a000 07:07 1442456                    /lib/x86_64-linux-gnu/libnss_files-2.24.so
7fa48d9ea000-7fa48d9eb000 r--p 0000a000 07:07 1442456                    /lib/x86_64-linux-gnu/libnss_files-2.24.so
7fa48d9eb000-7fa48d9ec000 rw-p 0000b000 07:07 1442456                    /lib/x86_64-linux-gnu/libnss_files-2.24.so
7fa48d9ec000-7fa48d9f2000 rw-p 00000000 00:00 0
7fa48d9f2000-7fa48dc57000 r-xp 00000000 07:07 657814                     /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
7fa48dc57000-7fa48de56000 ---p 00265000 07:07 657814                     /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
7fa48de56000-7fa48de74000 r--p 00264000 07:07 657814                     /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
7fa48de74000-7fa48de82000 rw-p 00282000 07:07 657814                     /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
7fa48de82000-7fa48de85000 rw-p 00000000 00:00 0
7fa48de85000-7fa48dee7000 r-xp 00000000 07:07 657815                     /usr/lib/x86_64-linux-gnu/libssl.so.1.1
7fa48dee7000-7fa48e0e7000 ---p 00062000 07:07 657815                     /usr/lib/x86_64-linux-gnu/libssl.so.1.1
7fa48e0e7000-7fa48e0eb000 r--p 00062000 07:07 657815                     /usr/lib/x86_64-linux-gnu/libssl.so.1.1
7fa48e0eb000-7fa48e0f1000 rw-p 00066000 07:07 657815                     /usr/lib/x86_64-linux-gnu/libssl.so.1.1
7fa48e0f1000-7fa48e2fd000 r-xp 00000000 07:07 1573026                    /opt/sensu/embedded/lib/libcrypto.so.1.0.0
7fa48e2fd000-7fa48e4fd000 ---p 0020c000 07:07 1573026                    /opt/sensu/embedded/lib/libcrypto.so.1.0.0
7fa48e4fd000-7fa48e518000 r--p 0020c000 07:07 1573026                    /opt/sensu/embedded/lib/libcrypto.so.1.0.0
7fa48e518000-7fa48e524000 rw-p 00227000 07:07 1573026                    /opt/sensu/embedded/lib/libcrypto.so.1.0.0
7fa48e524000-7fa48e527000 rw-p 00000000 00:00 0
7fa48e527000-7fa48e58a000 r-xp 00000000 07:07 1573040                    /opt/sensu/embedded/lib/libssl.so.1.0.0
7fa48e58a000-7fa48e78a000 ---p 00063000 07:07 1573040                    /opt/sensu/embedded/lib/libssl.so.1.0.0
7fa48e78a000-7fa48e78e000 r--p 00063000 07:07 1573040                    /opt/sensu/embedded/lib/libssl.so.1.0.0
7fa48e78e000-7fa48e795000 rw-p 00067000 07:07 1573040                    /opt/sensu/embedded/lib/libssl.so.1.0.0
7fa48e795000-7fa48e7aa000 r-xp 00000000 07:07 1573045                    /opt/sensu/embedded/lib/libz.so.1.2.8
7fa48e7aa000-7fa48e9a9000 ---p 00015000 07:07 1573045                    /opt/sensu/embedded/lib/libz.so.1.2.8
7fa48e9a9000-7fa48e9aa000 r--p 00014000 07:07 1573045                    /opt/sensu/embedded/lib/libz.so.1.2.8
7fa48e9aa000-7fa48e9ab000 rw-p 00015000 07:07 1573045                    /opt/sensu/embedded/lib/libz.so.1.2.8
7fa48e9ab000-7fa48e9f7000 r-xp 00000000 07:07 662059                     /usr/lib/x86_64-linux-gnu/libmariadb.so.3
7fa48e9f7000-7fa48ebf6000 ---p 0004c000 07:07 662059                     /usr/lib/x86_64-linux-gnu/libmariadb.so.3
7fa48ebf6000-7fa48ebfe000 r--p 0004b000 07:07 662059                     /usr/lib/x86_64-linux-gnu/libmariadb.so.3
7fa48ebfe000-7fa48ec00000 rw-p 00053000 07:07 662059                     /usr/lib/x86_64-linux-gnu/libmariadb.so.3
7fa48ec00000-7fa48ec02000 rw-p 00000000 00:00 0
7fa48ec02000-7fa48ec12000 r-xp 00000000 07:07 1574637                    /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/mysql2-0.4.8/lib/mysql2/mysql2.so
7fa48ec12000-7fa48ee12000 ---p 00010000 07:07 1574637                    /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/mysql2-0.4.8/lib/mysql2/mysql2.so
7fa48ee12000-7fa48ee13000 r--p 00010000 07:07 1574637                    /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/mysql2-0.4.8/lib/mysql2/mysql2.so
7fa48ee13000-7fa48ee14000 rw-p 00011000 07:07 1574637                    /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/mysql2-0.4.8/lib/mysql2/mysql2.so
7fa48ee14000-7fa48ee28000 r-xp 00000000 07:07 1576557                    /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/bigdecimal-1.3.5/lib/bigdecimal.so
7fa48ee28000-7fa48f027000 ---p 00014000 07:07 1576557                    /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/bigdecimal-1.3.5/lib/bigdecimal.so
7fa48f027000-7fa48f028000 r--p 00013000 07:07 1576557                    /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/bigdecimal-1.3.5/lib/bigdecimal.so
7fa48f028000-7fa48f029000 rw-p 00014000 07:07 1576557                    /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/bigdecimal-1.3.5/lib/bigdecimal.so
7fa48f029000-7fa48f05b000 r-xp 00000000 07:07 1573797                    /opt/sensu/embedded/lib/ruby/2.4.0/x86_64-linux/date_core.so
7fa48f05b000-7fa48f25b000 ---p 00032000 07:07 1573797                    /opt/sensu/embedded/lib/ruby/2.4.0/x86_64-linux/date_core.so
7fa48f25b000-7fa48f25c000 r--p 00032000 07:07 1573797                    /opt/sensu/embedded/lib/ruby/2.4.0/x86_64-linux/date_core.so
7fa48f25c000-7fa48f25d000 rw-p 00033000 07:07 1573797                    /opt/sensu/embedded/lib/ruby/2.4.0/x86_64-linux/date_core.so
7fa48f25d000-7fa48f25e000 rw-p 00000000 00:00 0
7fa48f25e000-7fa48f266000 r-xp 00000000 07:07 1573886                    /opt/sensu/embedded/lib/ruby/2.4.0/x86_64-linux/stringio.so
7fa48f266000-7fa48f465000 ---p 00008000 07:07 1573886                    /opt/sensu/embedded/lib/ruby/2.4.0/x86_64-linux/stringio.so
7fa48f465000-7fa48f466000 r--p 00007000 07:07 1573886                    /opt/sensu/embedded/lib/ruby/2.4.0/x86_64-linux/stringio.so
7fa48f466000-7fa48f467000 rw-p 00008000 07:07 1573886                    /opt/sensu/embedded/lib/ruby/2.4.0/x86_64-linux/stringio.so
7fa48f467000-7fa48f46a000 r-xp 00000000 07:07 1573849                    /opt/sensu/embedded/lib/ruby/2.4.0/x86_64-linux/enc/trans/transdb.so
7fa48f46a000-7fa48f669000 ---p 00003000 07:07 1573849                    /opt/sensu/embedded/lib/ruby/2.4.0/x86_64-linux/enc/trans/transdb.so
7fa48f669000-7fa48f66a000 r--p 00002000 07:07 1573849                    /opt/sensu/embedded/lib/ruby/2.4.0/x86_64-linux/enc/trans/transdb.so
7fa48f66a000-7fa48f66b000 rw-p 00003000 07:07 1573849                    /opt/sensu/embedded/lib/ruby/2.4.0/x86_64-linux/enc/trans/transdb.so
7fa48f66b000-7fa48f66d000 r-xp 00000000 07:07 1573807                    /opt/sensu/embedded/lib/ruby/2.4.0/x86_64-linux/enc/encdb.so
7fa48f66d000-7fa48f86c000 ---p 00002000 07:07 1573807                    /opt/sensu/embedded/lib/ruby/2.4.0/x86_64-linux/enc/encdb.so
7fa48f86c000-7fa48f86d000 r--p 00001000 07:07 1573807                    /opt/sensu/embedded/lib/ruby/2.4.0/x86_64-linux/enc/encdb.so
7fa48f86d000-7fa48f86e000 rw-p 00002000 07:07 1573807                    /opt/sensu/embedded/lib/ruby/2.4.0/x86_64-linux/enc/encdb.so
7fa48f86e000-7fa48fa03000 r-xp 00000000 07:07 1442446                    /lib/x86_64-linux-gnu/libc-2.24.so
7fa48fa03000-7fa48fc03000 ---p 00195000 07:07 1442446                    /lib/x86_64-linux-gnu/libc-2.24.so
7fa48fc03000-7fa48fc07000 r--p 00195000 07:07 1442446                    /lib/x86_64-linux-gnu/libc-2.24.so
7fa48fc07000-7fa48fc09000 rw-p 00199000 07:07 1442446                    /lib/x86_64-linux-gnu/libc-2.24.so
7fa48fc09000-7fa48fc0d000 rw-p 00000000 00:00 0
7fa48fc0d000-7fa48fd10000 r-xp 00000000 07:07 1442450                    /lib/x86_64-linux-gnu/libm-2.24.so
7fa48fd10000-7fa48ff0f000 ---p 00103000 07:07 1442450                    /lib/x86_64-linux-gnu/libm-2.24.so
7fa48ff0f000-7fa48ff10000 r--p 00102000 07:07 1442450                    /lib/x86_64-linux-gnu/libm-2.24.so
7fa48ff10000-7fa48ff11000 rw-p 00103000 07:07 1442450                    /lib/x86_64-linux-gnu/libm-2.24.so
7fa48ff11000-7fa48ff19000 r-xp 00000000 07:07 1442448                    /lib/x86_64-linux-gnu/libcrypt-2.24.so
7fa48ff19000-7fa490119000 ---p 00008000 07:07 1442448                    /lib/x86_64-linux-gnu/libcrypt-2.24.so
7fa490119000-7fa49011a000 r--p 00008000 07:07 1442448                    /lib/x86_64-linux-gnu/libcrypt-2.24.so
7fa49011a000-7fa49011b000 rw-p 00009000 07:07 1442448                    /lib/x86_64-linux-gnu/libcrypt-2.24.so
7fa49011b000-7fa490149000 rw-p 00000000 00:00 0
7fa490149000-7fa49014c000 r-xp 00000000 07:07 1442449                    /lib/x86_64-linux-gnu/libdl-2.24.so
7fa49014c000-7fa49034b000 ---p 00003000 07:07 1442449                    /lib/x86_64-linux-gnu/libdl-2.24.so
7fa49034b000-7fa49034c000 r--p 00002000 07:07 1442449                    /lib/x86_64-linux-gnu/libdl-2.24.so
7fa49034c000-7fa49034d000 rw-p 00003000 07:07 1442449                    /lib/x86_64-linux-gnu/libdl-2.24.so
7fa49034d000-7fa490365000 r-xp 00000000 07:07 1442461                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7fa490365000-7fa490564000 ---p 00018000 07:07 1442461                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7fa490564000-7fa490565000 r--p 00017000 07:07 1442461                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7fa490565000-7fa490566000 rw-p 00018000 07:07 1442461                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7fa490566000-7fa49056a000 rw-p 00000000 00:00 0
7fa49056a000-7fa490858000 r-xp 00000000 07:07 1573038                    /opt/sensu/embedded/lib/libruby.so.2.4.1
7fa490858000-7fa490a57000 ---p 002ee000 07:07 1573038                    /opt/sensu/embedded/lib/libruby.so.2.4.1
7fa490a57000-7fa490a5d000 r--p 002ed000 07:07 1573038                    /opt/sensu/embedded/lib/libruby.so.2.4.1
7fa490a5d000-7fa490a60000 rw-p 002f3000 07:07 1573038                    /opt/sensu/embedded/lib/libruby.so.2.4.1
7fa490a60000-7fa490a70000 rw-p 00000000 00:00 0
7fa490a70000-7fa490a93000 r-xp 00000000 07:07 1441818                    /lib/x86_64-linux-gnu/ld-2.24.so
7fa490b19000-7fa490b1d000 r--s 00000000 07:07 1572936                    /opt/sensu/embedded/bin/ruby
7fa490b1d000-7fa490c4f000 rw-p 00000000 00:00 0
7fa490c4f000-7fa490c56000 r--s 00000000 07:07 660716                     /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
7fa490c56000-7fa490c87000 r--p 00000000 07:07 657802                     /usr/lib/locale/C.UTF-8/LC_CTYPE
7fa490c87000-7fa490c8b000 rw-p 00000000 00:00 0
7fa490c8c000-7fa490c8d000 ---p 00000000 00:00 0
7fa490c8d000-7fa490c93000 rw-p 00000000 00:00 0
7fa490c93000-7fa490c94000 r--p 00023000 07:07 1441818                    /lib/x86_64-linux-gnu/ld-2.24.so
7fa490c94000-7fa490c95000 rw-p 00024000 07:07 1441818                    /lib/x86_64-linux-gnu/ld-2.24.so
7fa490c95000-7fa490c96000 rw-p 00000000 00:00 0
7ffdb85e4000-7ffdb8de3000 rw-p 00000000 00:00 0                          [stack]
7ffdb8df0000-7ffdb8df3000 r--p 00000000 00:00 0                          [vvar]
7ffdb8df3000-7ffdb8df5000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]


[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

[1]    15323 abort      ./check-percona-cluster-size.rb --user xxxxxx --password xxxxxx
```

Please note that using the official mariadb apt repository, `libmariadb-dev` is installed instead of `libmysqlclient-dev`.

I'm not  a ruby expert, bug i guess it could be related to the using of outdated mysql2 gem (0.4.8 vs 0.5.2)

**Comment by majormoses** [comment]
I dont have much experience with mariadb vs mysql compatibility issues. I looked at https://github.com/brianmario/mysql2/releases/tag/0.5.0 and there are some breaking changes, I would have to look at what the current supported versions of mysql are and if its something we can can stomach doing (in a major release). Also I note that this is a percona specific repo (although it should have most mysql compatibility) have you tried the more vanilla mysql plugins? https://github.com/sensu-plugins/sensu-plugins-mysql

**Comment by nervo** [comment]
@majormoses we are both using mysql and percona sensu plugin for their complementarity (such as aliveness on mysql side and galera cluster-size on percona side)
If that's the question, we don't have such issue with sensu-plugins-mysql :)

**Comment by nervo** [comment]
@majormoses  feel free to ask me for any tests
